-name: Configure my Application Server
  hosts: EC2
  vars: 
    ansible_python_interpreter: /usr/bin/python3.9
    ecr_registry_url: 210650517739.dkr.ecr.us-west-2.amazonaws.com
    ecr_repository_name: devopsproject
    ecr_tag: latest
    container_name: WebApp
    container_port: 80
    aws_region: us-west-2
    
  tasks: 
  -name: installing docker 
    apt:
      name: docker.io
      state: latest

  -name: Add ubuntu user to group docker 
    user:
      name: ubuntu
      groups: docker

  -name: Start Docker service
    service:
      name: docker
      state: started

  -name: Log into ECR registry
    shell: $(aws ecr get-login --no-include-email --region {{ ansible_ec2_placement_region }})

  -name: Pull docker image from ECR 
    shell: docker pull {{ ecr_registry_url }}/{{ ecr_repository_name }}:{{ ecr_tag }}

  -name: Build Docker container 
    shell: docker build -t {{container name}}

  -name: Stop existing Docker Container 
    shell: docker stop {{ container_name }} || true 

  -name: Remove existing Docker Container 
    shell: docker rm {{ container_name }} || true 

  -name: Run Docker Container 
    shell: docker run -d -p {{ container_port }}:80 --name {{ container_name }} {{ container_name }}

  



